# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/a/rotator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/a/rotator/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/a/rotator/build/CMakeFiles /home/a/rotator/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/a/rotator/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/glm/CMakeFiles/uninstall.dir/build.make 3rdparty/glm/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named stb

# Build rule for target.
stb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb
.PHONY : stb

# fast build rule for target.
stb/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/stb/CMakeFiles/stb.dir/build.make 3rdparty/stb/CMakeFiles/stb.dir/build
.PHONY : stb/fast

demo.o: demo.cc.o
.PHONY : demo.o

# target to build an object file
demo.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/demo.cc.o
.PHONY : demo.cc.o

demo.i: demo.cc.i
.PHONY : demo.i

# target to preprocess a source file
demo.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/demo.cc.i
.PHONY : demo.cc.i

demo.s: demo.cc.s
.PHONY : demo.s

# target to generate assembly for a file
demo.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/demo.cc.s
.PHONY : demo.cc.s

fontcache.o: fontcache.cc.o
.PHONY : fontcache.o

# target to build an object file
fontcache.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/fontcache.cc.o
.PHONY : fontcache.cc.o

fontcache.i: fontcache.cc.i
.PHONY : fontcache.i

# target to preprocess a source file
fontcache.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/fontcache.cc.i
.PHONY : fontcache.cc.i

fontcache.s: fontcache.cc.s
.PHONY : fontcache.s

# target to generate assembly for a file
fontcache.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/fontcache.cc.s
.PHONY : fontcache.cc.s

ioutil.o: ioutil.cc.o
.PHONY : ioutil.o

# target to build an object file
ioutil.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/ioutil.cc.o
.PHONY : ioutil.cc.o

ioutil.i: ioutil.cc.i
.PHONY : ioutil.i

# target to preprocess a source file
ioutil.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/ioutil.cc.i
.PHONY : ioutil.cc.i

ioutil.s: ioutil.cc.s
.PHONY : ioutil.s

# target to generate assembly for a file
ioutil.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/ioutil.cc.s
.PHONY : ioutil.cc.s

lazytexture.o: lazytexture.cc.o
.PHONY : lazytexture.o

# target to build an object file
lazytexture.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lazytexture.cc.o
.PHONY : lazytexture.cc.o

lazytexture.i: lazytexture.cc.i
.PHONY : lazytexture.i

# target to preprocess a source file
lazytexture.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lazytexture.cc.i
.PHONY : lazytexture.cc.i

lazytexture.s: lazytexture.cc.s
.PHONY : lazytexture.s

# target to generate assembly for a file
lazytexture.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lazytexture.cc.s
.PHONY : lazytexture.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cc.s
.PHONY : main.cc.s

mesh.o: mesh.cc.o
.PHONY : mesh.o

# target to build an object file
mesh.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/mesh.cc.o
.PHONY : mesh.cc.o

mesh.i: mesh.cc.i
.PHONY : mesh.i

# target to preprocess a source file
mesh.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/mesh.cc.i
.PHONY : mesh.cc.i

mesh.s: mesh.cc.s
.PHONY : mesh.s

# target to generate assembly for a file
mesh.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/mesh.cc.s
.PHONY : mesh.cc.s

shadermanager.o: shadermanager.cc.o
.PHONY : shadermanager.o

# target to build an object file
shadermanager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shadermanager.cc.o
.PHONY : shadermanager.cc.o

shadermanager.i: shadermanager.cc.i
.PHONY : shadermanager.i

# target to preprocess a source file
shadermanager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shadermanager.cc.i
.PHONY : shadermanager.cc.i

shadermanager.s: shadermanager.cc.s
.PHONY : shadermanager.s

# target to generate assembly for a file
shadermanager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shadermanager.cc.s
.PHONY : shadermanager.cc.s

shaderprogram.o: shaderprogram.cc.o
.PHONY : shaderprogram.o

# target to build an object file
shaderprogram.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shaderprogram.cc.o
.PHONY : shaderprogram.cc.o

shaderprogram.i: shaderprogram.cc.i
.PHONY : shaderprogram.i

# target to preprocess a source file
shaderprogram.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shaderprogram.cc.i
.PHONY : shaderprogram.cc.i

shaderprogram.s: shaderprogram.cc.s
.PHONY : shaderprogram.s

# target to generate assembly for a file
shaderprogram.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shaderprogram.cc.s
.PHONY : shaderprogram.cc.s

shake.o: shake.cc.o
.PHONY : shake.o

# target to build an object file
shake.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shake.cc.o
.PHONY : shake.cc.o

shake.i: shake.cc.i
.PHONY : shake.i

# target to preprocess a source file
shake.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shake.cc.i
.PHONY : shake.cc.i

shake.s: shake.cc.s
.PHONY : shake.s

# target to generate assembly for a file
shake.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shake.cc.s
.PHONY : shake.cc.s

spritebatcher.o: spritebatcher.cc.o
.PHONY : spritebatcher.o

# target to build an object file
spritebatcher.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/spritebatcher.cc.o
.PHONY : spritebatcher.cc.o

spritebatcher.i: spritebatcher.cc.i
.PHONY : spritebatcher.i

# target to preprocess a source file
spritebatcher.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/spritebatcher.cc.i
.PHONY : spritebatcher.cc.i

spritebatcher.s: spritebatcher.cc.s
.PHONY : spritebatcher.s

# target to generate assembly for a file
spritebatcher.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/spritebatcher.cc.s
.PHONY : spritebatcher.cc.s

texture.o: texture.cc.o
.PHONY : texture.o

# target to build an object file
texture.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/texture.cc.o
.PHONY : texture.cc.o

texture.i: texture.cc.i
.PHONY : texture.i

# target to preprocess a source file
texture.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/texture.cc.i
.PHONY : texture.cc.i

texture.s: texture.cc.s
.PHONY : texture.s

# target to generate assembly for a file
texture.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/texture.cc.s
.PHONY : texture.cc.s

textureatlas.o: textureatlas.cc.o
.PHONY : textureatlas.o

# target to build an object file
textureatlas.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/textureatlas.cc.o
.PHONY : textureatlas.cc.o

textureatlas.i: textureatlas.cc.i
.PHONY : textureatlas.i

# target to preprocess a source file
textureatlas.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/textureatlas.cc.i
.PHONY : textureatlas.cc.i

textureatlas.s: textureatlas.cc.s
.PHONY : textureatlas.s

# target to generate assembly for a file
textureatlas.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/textureatlas.cc.s
.PHONY : textureatlas.cc.s

textureatlaspage.o: textureatlaspage.cc.o
.PHONY : textureatlaspage.o

# target to build an object file
textureatlaspage.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/textureatlaspage.cc.o
.PHONY : textureatlaspage.cc.o

textureatlaspage.i: textureatlaspage.cc.i
.PHONY : textureatlaspage.i

# target to preprocess a source file
textureatlaspage.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/textureatlaspage.cc.i
.PHONY : textureatlaspage.cc.i

textureatlaspage.s: textureatlaspage.cc.s
.PHONY : textureatlaspage.s

# target to generate assembly for a file
textureatlaspage.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/textureatlaspage.cc.s
.PHONY : textureatlaspage.cc.s

uipainter.o: uipainter.cc.o
.PHONY : uipainter.o

# target to build an object file
uipainter.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/uipainter.cc.o
.PHONY : uipainter.cc.o

uipainter.i: uipainter.cc.i
.PHONY : uipainter.i

# target to preprocess a source file
uipainter.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/uipainter.cc.i
.PHONY : uipainter.cc.i

uipainter.s: uipainter.cc.s
.PHONY : uipainter.s

# target to generate assembly for a file
uipainter.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/uipainter.cc.s
.PHONY : uipainter.cc.s

wobble.o: wobble.cc.o
.PHONY : wobble.o

# target to build an object file
wobble.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/wobble.cc.o
.PHONY : wobble.cc.o

wobble.i: wobble.cc.i
.PHONY : wobble.i

# target to preprocess a source file
wobble.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/wobble.cc.i
.PHONY : wobble.cc.i

wobble.s: wobble.cc.s
.PHONY : wobble.s

# target to generate assembly for a file
wobble.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/wobble.cc.s
.PHONY : wobble.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... game"
	@echo "... stb"
	@echo "... demo.o"
	@echo "... demo.i"
	@echo "... demo.s"
	@echo "... fontcache.o"
	@echo "... fontcache.i"
	@echo "... fontcache.s"
	@echo "... ioutil.o"
	@echo "... ioutil.i"
	@echo "... ioutil.s"
	@echo "... lazytexture.o"
	@echo "... lazytexture.i"
	@echo "... lazytexture.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mesh.o"
	@echo "... mesh.i"
	@echo "... mesh.s"
	@echo "... shadermanager.o"
	@echo "... shadermanager.i"
	@echo "... shadermanager.s"
	@echo "... shaderprogram.o"
	@echo "... shaderprogram.i"
	@echo "... shaderprogram.s"
	@echo "... shake.o"
	@echo "... shake.i"
	@echo "... shake.s"
	@echo "... spritebatcher.o"
	@echo "... spritebatcher.i"
	@echo "... spritebatcher.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
	@echo "... textureatlas.o"
	@echo "... textureatlas.i"
	@echo "... textureatlas.s"
	@echo "... textureatlaspage.o"
	@echo "... textureatlaspage.i"
	@echo "... textureatlaspage.s"
	@echo "... uipainter.o"
	@echo "... uipainter.i"
	@echo "... uipainter.s"
	@echo "... wobble.o"
	@echo "... wobble.i"
	@echo "... wobble.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

